services:
  - type: web
    name: trading-agent
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
